projectTitle = "Task Life"
modId = "task_life"
githubRepo = "theendercore/TaskLife"
discordServerInviteId = "KZ5Q364hEg"
authors = [ "TheEnderCore" ]
majorMinecraftVersion = "1.20"
minecraftVersion = "1.20.2"
fabricLoaderVersion = "0.14.24"
fabricApiVersion = "0.90.7+1.20.2"
fabricLangKotlinVersion = "1.10.14+kotlin.1.9.20"
license = "MIT"
modules = [ ]

[mappings]
    # You have 6 mapping types
    # MOJANG: The official Mojang mappings
    # YARN: Yarn mappings
    # PARCHMENT: Parchment mappings
    # QUILT: Quilt mappings
    # MOJPARCH: Parchment layered on top of the official Mojang mappings
    # MOJYARN: Yarn layered on top of the official Mojang mappings
    type = "QUILT"
    version = "1.20.2+build.3"